on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://naritanara.xyz
    
    steps:
    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Connect, pull and build
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && trunk build --dist ${{ secrets.DEPLOY_DIR }} && exit"
    - name: Clean up
      run: rm -rf ~/.ssh
